"""Fixed categorization rules.

This module contains static keyword-based fallback rules. Learned rules saved
from the dashboard are applied before these rules.
"""


FIXED_RULES: dict[str, str] = {
    "zurich": "Seguros",
    "medicare": "Medicare",
    "meo": "Telecom",
    "vodafone": "Telecom",
    "nos": "Telecom",
    "viaverde": "Transportes",
    "tmp": "Transportes",
    "uber": "Transportes",
    "bolt": "Transportes",
    "continente": "Supermercado",
    "mercadona": "Supermercado",
    "pingo doce": "Supermercado",
    "lidl": "Supermercado",
    "auchan": "Supermercado",
    "spar": "Supermercado",
    "super 2000": "Supermercado",
    "ikea": "Supermercado",
    "makro": "Supermercado",
    "talho": "Supermercado",
    "mercado": "Supermercado",
    "mercearia": "Supermercado",
    "cafe bom dia": "Alimentação",
    "massas e temperos": "Alimentação",
    "temperos porto": "Alimentação",
    "c mara municipal": "Alimentação Escolar",
    "farmacia": "Saúde",
    "paulo alexandre antunes": "Alimentação/Ovos",
    "llaollao": "Restaurantes e Cafés",
    "airwallet": "Lavanderia",
    "wells": "Saúde",
    "lusiadas": "Saúde",
    "dgaj": "Documentos PT",
    "worten": "Tecnologia",
    "temu": "Compras Online",
    "amazon": "Compras Online",
    "ebay": "Compras Online",
    "shopee": "Compras Online",
    "aliexpress": "Compras Online",
    "mb way": "Transferência",
    "trf p/": "Transferência",
    "agua": "Água",
    "aguas": "Água",
    "energia": "Energia",
    "paulo": "Arrendamento",
    "ana": "Arrendamento",
}
